run all deployments in single job

diff --git a/.github/workflows/push_images.yml b/.github/workflows/push_images.yml
--- a/.github/workflows/push_images.yml
+++ b/.github/workflows/push_images.yml
@@ -14,229 +14,214 @@ jobs:
     env:
       REGISTRY_URL : ${{ secrets.REGISTRY }}
       GENERIC_IMAGE_URL : ${{ secrets.REGISTRY }}/cloud_editor_generic:${{ secrets.VERSION }}
-    
-    runs-on: ubuntu-latest
-
-    steps:
-      - uses: actions/checkout@v3
-      - uses: docker/login-action@v2
-        with:
-          registry: ${{ secrets.REGISTRY }}
-          username: ${{ secrets.USERNAME }}
-          password: ${{ secrets.TOKEN }}
-      - name: Build the generic cloud editor
-        run: make generic_image && docker tag $(make get_generic_image) $GENERIC_IMAGE_URL && docker push $GENERIC_IMAGE_URL && docker rm $(make get_generic_image) $GENERIC_IMAGE_URL
-      
-    
-  deploy_nodejs:
-  
-    environment: production
-    runs-on: ubuntu-latest
-    
-    env:
-      REGISTRY_URL: ${{ secrets.REGISTRY }}
       NODEJS_IMAGE_URL: ${{ secrets.REGISTRY }}/cloud_editor_nodejs:${{ secrets.VERSION }}
-      
-    steps:
-      - uses: actions/checkout@v3
-      - uses: docker/login-action@v2
-        with:
-          registry: ${{ secrets.REGISTRY }}
-          username: ${{ secrets.USERNAME }}
-          password: ${{ secrets.TOKEN }}
-      - name: Push cloud editor nodejs image
-        run: make nodejs_image && docker tag $(make get_nodejs_image) $NODEJS_IMAGE_URL && docker push $NODEJS_IMAGE_URL && docker rm $(make get_nodejs_image) $NODEJS_IMAGE_URL
-      
-  push_golang:
-  
-    environment: production
-    runs-on: ubuntu-latest
-    
-    env:
-      REGISTRY_URL: ${{ secrets.REGISTRY }}
       GOLANG_IMAGE_URL: ${{ secrets.REGISTRY }}/cloud_editor_golang:${{ secrets.VERSION }}
-      
-    steps:
-      - uses: actions/checkout@v3
-      - uses: docker/login-action@v2
-        with:
-          registry: ${{ secrets.REGISTRY }}
-          username: ${{ secrets.USERNAME }}
-          password: ${{ secrets.TOKEN }}
-      - name: Push cloud editor golang images
-        run: make golang_image && docker tag $(make get_golang_image) $GOLANG_IMAGE_URL && docker push $GOLANG_IMAGE_URL && docker rm $(make get_golang_image) $GOLANG_IMAGE_URL
-      
-  push_python_spark:
-  
-    environment: production
-    runs-on: ubuntu-latest
-    
-    env:
-      REGISTRY_URL: ${{ secrets.REGISTRY }}
       PYTHON_SPARK_IMAGE_URL : ${{ secrets.REGISTRY }}/cloud_editor_python:${{ secrets.VERSION }}
-      
-    steps:
-      - uses: actions/checkout@v3
-      - uses: docker/login-action@v2
-        with:
-          registry: ${{ secrets.REGISTRY }}
-          username: ${{ secrets.USERNAME }}
-          password: ${{ secrets.TOKEN }}
-      - name: push cloud editor python image
-        run: make python_spark_image && docker tag $(make get_python_spark_image) $PYTHON_SPARK_IMAGE_URL && docker push $PYTHON_SPARK_IMAGE_URL && docker rm $(make get_python_spark_image) $PYTHON_SPARK_IMAGE_URL
-  
-  push_python_datascience_image:
-    
-    environment: production
-    runs-on: ubuntu-latest
-    
-    env:
-      REGISTRY_URL: ${{ secrets.REGISTRY }}
       PYTHON_DATASCIENCE_IMAGE_URL : ${{ secrets.REGISTRY }}/cloud_editor_python_datascience:${{ secrets.VERSION }}
-      
-    steps:
-      - uses: actions/checkout@v3
-      - uses: docker/login-action@v2
-        with:
-          registry: ${{ secrets.REGISTRY }}
-          username: ${{ secrets.USERNAME }}
-          password: ${{ secrets.TOKEN }}
-      - name: push cloud editor python datascience image
-        run: make python_datascience_image && docker tag $(make get_python_datascience_image) $PYTHON_DATASCIENCE_IMAGE_URL && docker push $PYTHON_DATASCIENCE_IMAGE_URL && docker rm $PYTHON_DATASCIENCE_IMAGE_URL $(make get_python_datascience_image)
-      
-      
-  push_python_anaconda_image:
-    
-    environment: production
-    runs-on: ubuntu-latest
-    
-    env:
-      REGISTRY_URL : ${{ secrets.REGISTRY }}
       PYTHON_ANACONDA_IMAGE_URL: ${{ secrets.REGISTRY }}/cloud_editor_python_anaconda:${{ secrets.VERSION }}
-      
-    steps:
-      - uses: actions/checkout@v3
-      - uses: docker/login-action@v2
-        with:
-          registry: ${{ secrets.REGISTRY }}
-          username: ${{ secrets.USERNAME }}
-          password: ${{ secrets.TOKEN }}
-      - name: push the python anaconda image
-        run: make python_anaconda_image && docker tag $(make get_python_anaconda_image) $PYTHON_ANACONDA_IMAGE_URL && cker push $PYTHON_ANACONDA_IMAGE_URL && cker rm $(make get_python_anaconda_image) $PYTHON_ANACONDA_IMAGE_URL
-      
-      
-  push_flutter_image:
-    
-    environment: production
-    runs-on: ubuntu-latest
-    
-    env:
-      REGISTRY_URL: ${{ secrets.REGISTRY }}
       FLUTTER_IMAGE_URL: ${{ secrets.REGISTRY }}/cloud_editor_flutter:${{ secrets.VERSION }}
-      
-    steps:
-      - uses: actions/checkout@v3
-      - uses: docker/login-action@v2
-        with:
-          registry: ${{ secrets.REGISTRY }}
-          username: ${{ secrets.USERNAME }}
-          password: ${{ secrets.TOKEN }}
-      - name: push the cloud editor flutter image
-        run: make flutter_image && docker tag $(make get_flutter_image) $FLUTTER_IMAGE_URL && docker push $FLUTTER_IMAGE_URL && docker rm $(make get_flutter_image) $FLUTTER_IMAGE_URL
-      
-  push_java_intellij_image:
-    
-    environment: production
-    runs-on: ubuntu-latest
-    
-    env:
-      REGISTRY_URL: ${{ secrets.REGISTRY }}
       JAVA_INTELLIJ_IMAGE_URL: ${{ secrets.REGISTRY }}/cloud_editor_java_intellij:${{ secrets.VERSION }}
-      
-    steps:
-      - uses: actions/checkout@v3
-      - uses: docker/login-action@v2
-        with:
-          registry: ${{ secrets.REGISTRY }}
-          username: ${{ secrets.USERNAME }}
-          password: ${{ secrets.TOKEN }}
-      - name: push the cloud editor java intellij image
-        run: make java_intellij && docker tag $(make get_java_intellij_image) && docker push $JAVA_INTELLIJ_IMAGE_URL && docker rm $(make get_java_intellij_image) $JAVA_INTELLIJ_IMAGE_URL
-      
-      
-  push_goland:
-  
-    environment: production
-    runs-on: ubuntu-latest
-    
-    env:
-      REGISTRY_URL: ${{ secrets.REGISTRY }}
       GOLAND_IMAGE_URL: ${{ secrets.REGISTRY }}/goland_go:${{ secrets.VERSION }}
-      
-    steps:
-      - uses: actions/checkout@v3
-      - uses: docker/login-action@v2
-        with:
-          registry: ${{ secrets.REGISTRY }}
-          username: ${{ secrets.USERNAME }}
-          password: ${{ secrets.TOKEN }}
-      - name: push goland image
-        run: make goland && docker tag $(make get_goland_image) $GOLAND_IMAGE_URL && docker push $GOLAND_IMAGE_URL && docker rm $(make get_goland_image) $GOLAND_IMAGE_URL
-      
-      
-  push_pycharm_image:
-    
-    environment: production
-    runs-on: ubuntu-latest
-    
-    env:
-      REGISTRY_URL: ${{ secrets.REGISTRY }}
       PYCHARM_IMAGE_URL: ${{ secrets.REGISTRY }}/pycharm_python:${{ secrets.VERSION }}
-      
-    steps:
-      - uses: actions/checkout@v3
-      - uses: docker/login-action@v2
-        with:
-          registry: ${{ secrets.REGISTRY }}
-          username: ${{ secrets.USERNAME }}
-          password: ${{ secrets.TOKEN }}
-      - name: push pycharm image
-        run: make pycharm && docker tag $(make get_pycharm_image) $PYCHARM_IMAGE_URL && docker push $PYCHARM_IMAGE_URL && docker rm $PYCHARM_IMAGE_URL $(make get_pycharm_image)
-      
-  push_phpstorm_image:
-    
-    environment: production
-    runs-on: ubuntu-latest
-    
-    env:
-      REGISTRY_URL: ${{ secrets.REGISTRY }}
       PHPSTORM_IMAGE_URL: ${{ secrets.REGISTRY }}/phpstorm_php:${{ secrets.VERSION }}
-      
-    steps:
-      - uses: actions/checkout@v3
-      - uses: docker/login-action@v2
-        with:
-          registry: ${{ secrets.REGISTRY }}
-          username: ${{ secrets.USERNAME }}
-          password: ${{ secrets.TOKEN }}
-      - name: push phpstorm image
-        run: make phpstorm && docker tag $(make get_phpstorm_image) $PHPSTORM_IMAGE_URL && docker push $PHPSTORM_IMAGE_URL && docker rm $PYCHARM_IMAGE_URL $(make get_phpstorm_image)
-    
-  push_android_studio_image:
-    
-    environment: production
-    runs-on: ubuntu-latest
-    
-    env:
-      REGISTRY_URL: ${{ secrets.REGISTRY }}
       ANDROID_IMAGE_URL: ${{ secrets.REGISTRY }}/android_studio:${{ secrets.VERSION }}
 
+    runs-on: ubuntu-latest
+
+
     steps:
       - uses: actions/checkout@v3
-      - uses: docker/login-action@v2
+
+
+      - name: Setup Google cloud SDK
+        uses: google-github-actions/setup-gcloud@v0
+        with:
+          project_id: ${{ secrets.GCP_PROJECT_ID }}
+          service_account_key: ${{ secrets.GCP_SA_KEY }}
+          export_default_credentials: true
+
+      
+      - name: Configure gcloud with docker
+        run: |
+          gcloud config set project ${{ secrets.PROJECT_NAME }}
+          gcloud auth configure-docker -q 
+
+        uses: docker/login-action@v2
         with:
           registry: ${{ secrets.REGISTRY }}
           username: ${{ secrets.USERNAME }}
           password: ${{ secrets.TOKEN }}
-      - name: push android studio image 
-        run: make android_studio ; docker tag $(make get_android_studio_image):$(make get_version) ; docker push $ANDROID_IMAGE_URL ; docker rm $ANDROID_IMAGE_URL $(make get_android_studio_image)
+
+      # Build the base image
+
+      - name: Build the base image
+        run: make base_image
+
+      # Build the generic cloud editor image 
+
+      - name: Build the generic cloud editor
+        run: make generic_image
+
+      - name: Tag new generic cloud editor image
+        run: docker tag $(make get_generic_image) $GENERIC_IMAGE_URL
+
+      - name: Push the generic cloud editor image
+        run: docker push $GENERIC_IMAGE_URL
+      
+      - name: Remove generic cloud editor image
+        run: docker rmi $(docker images -a | grep -v sn_base | grep -v IMAGE  |  awk {'print $3'}) || echo 'ignoring error'
+
+        # Build the nodejs image
+
+      - name: Build the nodejs cloud editor
+        run: make nodejs
+
+      - name: Tag new nodejs cloud editor image
+        run: docker tag $(make get_nodejs_image) $NODEJS_IMAGE_URL
+
+      - name: Push the nodejs cloud editor image
+        run: docker push $NODEJS_IMAGE
+      
+      - name: Remove nodejs cloud editor image
+        run: docker rmi $(docker images -a | grep -v sn_base | grep -v IMAGE  |  awk {'print $3'}) || echo 'ignoring error'
+
+        # Build golang image
+        
+      - name: Build the golang cloud editor
+        run: make golang_image
+
+      - name: Tag new golang cloud editor image
+        run: docker tag $(make get_golang_image) $GOLANG_IMAGE_URL
+
+      - name: Push the golang cloud editor image
+        run: docker push $GOLANG_IMAGE_URL 
+      
+      - name: Remove golang cloud editor image
+        run: docker rmi $(docker images -a | grep -v sn_base | grep -v IMAGE  |  awk {'print $3'}) || echo 'ignoring error'
+
+        # Build python spark
+
+      - name: Build the python spark cloud editor
+        run: make python_spark_image
+
+      - name: Tag new python spark cloud editor image
+        run: docker tag $(make get_python_spark_image) $PYTHON_SPARK_IMAGE_URL 
+
+      - name: Push the python spark cloud editor image
+        run: docker push $PYTHON_SPARK_IMAGE_URL
+      
+      - name: Remove python spark cloud editor image
+        run: docker rmi $(docker images -a | grep -v sn_base | grep -v IMAGE  |  awk {'print $3'}) || echo 'ignoring error'
+
+      # Build python datascience
+
+      - name: Build the python datascience cloud editor
+        run: make python_datascience_image
+
+      - name: Tag new python datascience cloud editor image
+        run: docker tag $(make get_python_datascience_image) $PYTHON_DATASCIENCE_IMAGE_URL 
+
+      - name: Push the python datascience cloud editor image
+        run: docker push $PYTHON_DATASCIENCE_IMAGE_URL 
+      
+      - name: Remove python datascience cloud editor image
+        run: docker rmi $(docker images -a | grep -v sn_base | grep -v IMAGE  |  awk {'print $3'}) || echo 'ignoring error'
+
+      # Build python anaconda
+
+      - name: Build the python anaconda cloud editor
+        run: make python_anaconda_image
+
+      - name: Tag new python anaconda cloud editor image
+        run: docker tag $(make get_python_anaconda_image) $PYTHON_ANACONDA_IMAGE_URL
+
+      - name: Push the python anaconda cloud editor image
+        run: docker push $PYTHON_ANACONDA_IMAGE_URL
+      
+      - name: Remove python anaconda cloud editor image
+        run: docker rmi $(docker images -a | grep -v sn_base | grep -v IMAGE  |  awk {'print $3'}) || echo 'ignoring error'
+
+
+      # Build flutter image 
+
+      - name: Build the flutter cloud editor
+        run: make flutter_image
+
+      - name: Tag new flutter cloud editor image
+        run: docker tag $(make get_flutter_image) $FLUTTER_IMAGE_URL
+
+      - name: Push the flutter cloud editor image
+        run:  docker push $FLUTTER_IMAGE_URL
+      
+      - name: Remove flutter cloud editor image
+        run: docker rmi $(docker images -a | grep -v sn_base | grep -v IMAGE  |  awk {'print $3'}) || echo 'ignoring error'
+
+        # Build Java Intellij image
+
+      - name: Build the java intellij cloud editor
+        run: make java_intellij
+
+      - name: Tag new java intellij cloud editor image
+        run: docker tag $(make get_java_intellij_image)
+
+      - name: Push the java intellij cloud editor image
+        run:  docker push $JAVA_INTELLIJ_IMAGE_URL 
+      
+      - name: Remove java intellij cloud editor image
+        run: docker rmi $(docker images -a | grep -v sn_base | grep -v IMAGE  |  awk {'print $3'}) || echo 'ignoring error'
+
+      # build Goland image
+
+      - name: Build the goland cloud editor
+        run: make goland 
+
+      - name: Tag new goland cloud editor image
+        run: docker tag $(make get_goland_image) $GOLAND_IMAGE_URL
+
+      - name: Push the goland cloud editor image
+        run:  docker push $GOLAND_IMAGE_URL
+      
+      - name: Remove Goland cloud editor image
+        run: docker rmi $(docker images -a | grep -v sn_base | grep -v IMAGE  |  awk {'print $3'}) || echo 'ignoring error'
+
+      # Build Pycharm image
+
+      - name: Build the Pycharm cloud editor
+        run:  make pycharm
+
+      - name: Tag new Pycharm cloud editor image
+        run: docker tag $(make get_pycharm_image) $PYCHARM_IMAGE_URL
+
+      - name: Push the Pycharm cloud editor image
+        run:  docker push $PYCHARM_IMAGE_URL 
+      
+      - name: Remove Pycharm cloud editor image
+        run: docker rmi $(docker images -a | grep -v sn_base | grep -v IMAGE  |  awk {'print $3'}) || echo 'ignoring error'
+
+      # Build phpstorm
+
+      - name: Build the PHPStorm cloud editor
+        run:  make phpstorm
+
+      - name: Tag new PHPStorm cloud editor image
+        run: docker tag $(make get_phpstorm_image) $PHPSTORM_IMAGE_URL
+
+      - name: Push the PHPStorm cloud editor image
+        run:  docker push $PHPSTORM_IMAGE_URL
+      
+      - name: Remove PHPstorm cloud editor image
+        run: docker rmi $(docker images -a | grep -v sn_base | grep -v IMAGE  |  awk {'print $3'}) || echo 'ignoring error'
+      
+      # Build Android studio
+
+      - name: Build the Android Studio cloud editor
+        run:  make android_studio
+
+      - name: Tag new Android studio cloud editor image
+        run: docker tag $(make get_android_studio_image):$(make get_version)
+
+      - name: Push the Android Studio cloud editor image
+        run:  docker push $ANDROID_IMAGE_URL
+      
+      - name: Remove Android Studio cloud editor image
+        run: docker rmi $(docker images -a | grep -v sn_base | grep -v IMAGE  |  awk {'print $3'}) || echo 'ignoring error'
